name: "Setup Just and UV"
description: "Setup just and uv without installing dependencies"
runs:
  using: "composite"
  steps:
    - name: Install just
      uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

    - name: Setup uv
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
      with:
        enable-cache: true
        version: "0.11.14"
