name: "Setup Just and UV"
description: "Setup just and uv without installing dependencies"
runs:
  using: "composite"
  steps:
    - name: Install just
      uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

    - name: Setup uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        enable-cache: true
        version: "0.11.14"
