name: Publish

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup environment
        uses: ./.github/actions/setup_just_and_uv/

      - name: Build and test package
        run: just build

      - name: Publish package
        run: just publish

  deploy-docs:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Deploy documentation
        run: just docs-test && just docs-deploy
